@startuml
(*) --> "검증된 가설이 충분히 모였는가?"
if "" then
	--> [yes] "충실도 지표 모델 수립시작"
else
	--> [no] "지표로 세울만한 가설을 세운다"
	--> if "가설을 검증한다" then
            --> [상관관계가 있음] "가설 추가"
            ------> "검증된 가설이 충분히 모였는가?"
        else
            --> [상관관계가 없음] "가설 폐기"
            --> "검증된 가설이 충분히 모였는가?"
        endif
endif


"충실도 지표 모델 수립시작" --> "테스트 결과 성능이 원하는 수준인가?"
if "" then
    --> [yes] (*)
else
    --> [no] "가설간의 비중 조절 및 다른 조합 시도"
    --> "테스트 결과 성능이 원하는 수준인가?"
endif

@enduml